name: tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          docker-compose -f docker-compose.kafka.yml up -d \
          && docker-compose -f app/src/tests/functional/docker-compose.yml up --build tests
        
